spring:
  kafka:
    bootstrap-servers: 192.168.3.201:9092, 192.168.3.202:9092, 192.168.3.203:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      group-id: group1
